-include .env
export VERSION_NUMBER = 1.2.0
export BUILD_NUMBER = 12000001

export NBG_APP_VERSION_NUMBER = 1.0.37
export NBG_APP_BUILD_NUMBER = 103700001
export EXTERNAL_PATH = 

generateVersionConstantsFile:
	echo '\n\n/* \nTHIS FILE IS AUTOGENERATED FROM MAKEFILE. DO NOT UPDATE IT\n*/\n\n' > VersionConstants.swift
	echo 'import Foundation\n' >> VersionConstants.swift
	echo 'public extension ENMobileSDK {' >> VersionConstants.swift
	echo '\tvar versionNumber: String { return "${VERSION_NUMBER}" }' >> VersionConstants.swift
	echo '\tvar buildNumber: String { return "${BUILD_NUMBER}" }' >> VersionConstants.swift
	echo '}' >> VersionConstants.swift


install: bootstrap project
project: xcodeproj_gen
install_dependencies: brew_install bundler bootstrap xcodeproj_gen swiftgen

brew_install:
	-brew update
	-brew bundle

bundler:
	sudo gem install bundler

bootstrap: 
	mint bootstrap
	arch -x86_64 bundle install --path vendor/bundler

xcodeproj_gen:
	make generateVersionConstantsFile
	mint run xcodegen xcodegen generate
	
clean:
	rm -rf *.xcodeproj

nuke: 
	make clean
	-rm Gemfile.lock
	-rm Brewfile.lock.json
	-rm -rf vendor
setup:
	make clean
	make brew_install	
	make bootstrap
	make project
	open *oj

exportFramework:
	sh script.sh
