

/* 
THIS FILE IS AUTOGENERATED FROM MAKEFILE. DO NOT UPDATE IT
*/


import Foundation

public extension ENMobileSDK {
	var versionNumber: String { return "1.2.0" }
	var buildNumber: String { return "12000001" }
}
